# Site settings
title: interma
description: > # this means to ignore newlines until "baseurl:"
    interma github blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://interma.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
